services:
  couchdb:
    image: couchdb:3
    container_name: couchdb_container
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    networks:
      - couch_network

  init-db:
    build:
       context: ../../
       dockerfile: Python/DockerFiles/CouchDB/Dockerfile
    container_name: init_db_container
    volumes:
      - ./output:/app/output
    depends_on:
      - couchdb
    restart: "no"
    networks:
      - couch_network

networks:
  couch_network:
    driver: bridge
