services:
  couchdb:
    image: couchdb:3
    container_name: couchdb_container
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      - ./couchdb_data:/opt/couchdb/data

volumes:
  couchdb_data:
    driver: local